apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: cv1-zaznam-chorob-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: cv1-zaznam-chorob-webapi-config
    literals:
      - database=project-cv1-zaznam-chorob
      - collection=project-cv1-zaznam-chorob
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: cv1-zaznam-chorob-webapi