/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {

	// CreatePatient Post /api/patients
	// Create a new patient
	CreatePatient(c *gin.Context)

	// GetPatients Get /api/patients
	// Get all patients
	GetPatients(c *gin.Context)
}
