/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

// MedicationsAPIService - interface for medications-related operations
type MedicationsAPIService interface {
	// Creates a new medication
	CreateMedication(c *gin.Context)

	// Gets all medications for a patient
	GetPatientMedications(c *gin.Context)

	// Updates an existing medication
	UpdateMedication(c *gin.Context)

	// Deletes a specific medication
	DeleteMedication(c *gin.Context)
}