/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type TreatmentsAPI interface {

	// CreateTreatment Post /api/patients/:patientId/illnesses/:illnessId/treatments
	// Create a new treatment record
	CreateTreatment(c *gin.Context)

	// DeleteTreatment Delete /api/patients/:patientId/illnesses/:illnessId/treatments/:treatmentId
	// Delete treatment record
	DeleteTreatment(c *gin.Context)

	// GetPatientTreatments Get /api/patients/:patientId/illnesses/:illnessId/treatments
	// Get treatment for a specific patient
	GetTreatments(c *gin.Context)

	// UpdatePatientTreatments Patch /api/patients/:patientId/illnesses/:illnessId/treatments/:treatmentId
	// Update treatment record
	UpdateTreatment(c *gin.Context)
}
