/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type TreatmentsAPI interface {


    // CreateTreatment Post /api/patients/:patientId/illnesses/:illnessId/treatments
    // Create a new treatment for an illness 
     CreateTreatment(c *gin.Context)

    // DeleteTreatment Delete /api/patients/:patientId/illnesses/:illnessId/treatments/:treatmentId
    // Delete a treatment 
     DeleteTreatment(c *gin.Context)

    // GetTreatments Get /api/patients/:patientId/illnesses/:illnessId/treatments
    // Get treatments for a patient's illness 
     GetTreatments(c *gin.Context)

    // UpdateTreatment Patch /api/patients/:patientId/illnesses/:illnessId/treatments/:treatmentId
    // Update a treatment 
     UpdateTreatment(c *gin.Context)

}