/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type UpdateSickLeaveEndDateRequest struct {

	// New sick leave end date
	SlUntil string `json:"sl_until"`
}
