/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Illness struct {

	// Unique identifier for the illness record
	Id string `json:"id"`

	// ID of the patient this illness record belongs to
	PatientId string `json:"patientId"`

	// Medical diagnosis
	Diagnosis string `json:"diagnosis"`

	// Start date of sick leave
	SlFrom string `json:"slFrom"`

	// End date of sick leave
	SlUntill string `json:"sl_untill"`

	// Additional notes about the illness or treatment
	Notes string `json:"notes,omitempty"`
}
