/*
 * Patient and Illness Management API
 *
 * Patient and Illness Management API
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Treatment struct {

	// Unique identifier for the treatment
	Id string `json:"id"`

	// Name of the treatment
	Name string `json:"name"`

	// Description of the treatment
	Description string `json:"description"`

	// Date when the treatment started
	StartDate string `json:"startDate"`

	// Date when the treatment ended
	EndDate string `json:"endDate"`
}
